### ISSUE TITLE
Issue with drupal8 blt multi site

### ISSUE THREAD

**Issue by sharique** [nalipaz/lando-acquia-multisite-recipe#2]
I created a site using blt and followed official docs(https://blt.readthedocs.io/en/9.x/multisite/) to create multisite. But second site (ads2.lndo.site ) showing 404.
Here is lando.yml file, can you tell me what I've doing wrong?
```
name: adstestmulti
recipe: drupal8
config:
  webroot: docroot
  appserver:
tooling:
  blt:
    service: appserver
    cmd: /usr/bin/blt
proxy:
  appserver:
    - adstestmulti.lndo.site
    - ads2.lndo.site

**Comment by SerShevchyk** [comment]
@sharique you use the wrong construction, try next
```
name: landomultisite
recipe: drupal8
config:
  framework: drupal8
  webroot: web
  php: 7.2
proxy:
  appserver:
    - es.test.lndo.site
    - uk.test.lndo.site
```
